# Generated by Django 4.0.6 on 2022-11-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_score_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='stars',
        ),
    ]
